name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: payquicker
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile-net8 --tag net8

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    # Push the Docker image to GitHub Container Registry
    - name: Push image to GitHub Container Registry
      run: |
        docker tag net8 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:net8
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:net8